# This file was generated by GoReleaser. DO NOT EDIT.
cask "hooktap" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d3119f254378f0e01512dd2fa12e941f471b8b783596791b13cfd683780c0742"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a96e0d4e7389ba8228c70198a03b4d62a43393528ff4490e5cb961ee82078590"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "97a2ad0dab1ff20733dc7e7347a42122458f55bbec4548e3e71cc03a444aeff1"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "558c9238b8d24e75e2556fbfff5c3b904a2d47d94cf4233b9989383cc658cebc"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hooktap"
  desc "Send webhook events to the HookTap app from your terminal"
  homepage "https://hooktap.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hooktap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/hooktap"]
    end
  end

  # No zap stanza required

end
