# This file was generated by GoReleaser. DO NOT EDIT.
cask "hooktap" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "9f156b964f69f453a9341bbc65993bb44bc92151f1045bce15f0b53327e24455"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ad0f2d65923e64f5423326aa9a53f97d441713bc0228470ea69887c88d38806"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63c1d7598b99ac3c3825761278907786a303ec16246b77e36b3d9087a84b3dba"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67c39f5ebfa199810a71e925cb7c2ac791e529373ae455029d463e58f22d8d31"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hooktap"
  desc "Send webhook events to the HookTap app from your terminal"
  homepage "https://hooktap.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hooktap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/hooktap"]
    end
  end

  # No zap stanza required

end
