# This file was generated by GoReleaser. DO NOT EDIT.
cask "hooktap" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d69fcfcd7d44f69f89d26af973084b1eb1ef60bac8648d968667d93799e24eff"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "adbcb4d032b03912acca1848c8ac4a7ae54a18f36ad0861ae4a6e8bf1df6e8e3"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cfe2b34d205f86d3b4e8f532b5e3be4ff8787afe92daf5c55135863fa245a048"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "54fce609983f3d8970770d5290db8635c7c1ca8835ecca4d4afb9edf86d2eb54"
      url "https://github.com/HookTap/hooktap-cli/releases/download/v#{version}/hooktap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hooktap"
  desc "Send webhook events to the HookTap app from your terminal"
  homepage "https://hooktap.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hooktap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/hooktap"]
    end
  end

  # No zap stanza required

end
